#!/bin/bash

#📦 RunPod Ollama Template ConfigurationWhen you want to deploy a template on RunPod, you do not write a script;
# instead, you fill out a form in the Templates tab of your RunPod dashboard. Use these exact
# parameters:FieldConfiguration ValueTemplate NameOllama-API-ServerContainer Imageollama/ollama:latest
# (or the official runpod/ollama community tag)Container Disk10 GBVolume Disk50 GB (Crucial: This
# gives you enough space to download the 43GB DeepSeek 70B model)
# Exposed Ports11434/tcpEnvironment VariablesKey: Ollama_HOST | Value: 0.0.0.0
clear
echo "=========================================================="
echo "🌐 OLLAMA REMOTE TEMPLATE CLIENT ROUTER"
echo "=========================================================="

# 1. Ask for the public proxy URL generated by the RunPod Template
read -p "🔹 Paste your RunPod Public Proxy URL (Port 11434): " PROXY_URL

if [ -z "$PROXY_URL" ]; then
    echo "❌ Error: Proxy URL cannot be empty."
    exit 1
fi

# Strip trailing slashes to avoid API path formatting breaks
PROXY_URL="${PROXY_URL%/}"

echo -e "\n🔗 Connected to RunPod Template container..."
echo "📥 Commanding remote server to download and initialize DeepSeek-R1:70B..."
echo "----------------------------------------------------------"

# 2. Re-route your local terminal client tool to point to the cloud container's URL
export OLLAMA_HOST="$PROXY_URL"

# 3. Instruct the template container to pull and immediately boot the model
ollama run deepseek-r1:70b

echo "----------------------------------------------------------"
echo "🖥️  Session Closed. Local terminal client reverted to native modes."
echo "⚠️  Remember to TERMINATE your RunPod worker instance to stop billing!"
